name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cmake -B build
            cmake --build build 

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ctest --test-dir build --output-on-failure --output-junit junit.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/build/junit.xml'

